field: ae375820-3398-4233-97c9-880f9bc88381 # Hero Image
fieldLayouts:
  3579b715-4d6a-42dc-8222-21c82dc69f7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1a647170-6b92-46d3-a5af-91b1883af9f0 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b66b7619-2e4f-4522-ba9d-672bee298f22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47055c18-ba46-4bb5-b886-7609129c8ab3 # Greyscale
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4d6df85-129f-45d6-91cd-004e139c2e54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 152aa502-7617-4eba-be65-f4c60fcbc01a
        userCondition: null
fields:
  1a647170-6b92-46d3-a5af-91b1883af9f0: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:88345c9b-bba7-481d-b7be-a56f256bad79' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:88345c9b-bba7-481d-b7be-a56f256bad79' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:88345c9b-bba7-481d-b7be-a56f256bad79' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  47055c18-ba46-4bb5-b886-7609129c8ab3: # Greyscale
    columnSuffix: ndhdcphj
    contentColumnType: boolean
    fieldGroup: null
    handle: greyscale
    instructions: 'This will automatically make any image uploaded here greyscale (or the Image Thumbnail, if no hero image is selected).'
    name: Greyscale
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: heroImage
name: 'Hero Image'
sortOrder: 1
