field: 2fb3dcfb-de61-404d-a714-a5cc5585bc1d # Content Blocks
fieldLayouts:
  1bd210be-001f-4e52-a401-bb949c452b9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 017fdb0e-1650-4bed-aa88-2320f4c5101a # Block Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 659fef91-0f1b-4fbb-8a01-c7b78502fc69
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7bee1e32-7f18-4448-95ee-9cfc3b0ed3db # Block Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a1d383c-6c36-4cbe-92ce-bb57d5be6675
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7cf7c89c-868b-4bd0-8296-177d113c53b4 # Slider Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf410bb7-ade1-4db0-9a3a-cc327c095e00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78b7ec25-ca51-442f-81b1-516f79f96d66 # Image(s)
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48860578-6a30-4d66-ad2f-cd45118d185a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1432ecc-ae14-49e5-8c4b-0bea71d153fd
        userCondition: null
fields:
  7bee1e32-7f18-4448-95ee-9cfc3b0ed3db: # Block Width
    columnSuffix: dltbaskl
    contentColumnType: string
    fieldGroup: null
    handle: blockWidth
    instructions: 'Note: this will only apply for the Slideshow slider type.'
    name: 'Block Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full width'
            -
              - value
              - fullWidth
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Contained
            -
              - value
              - contained
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  7cf7c89c-868b-4bd0-8296-177d113c53b4: # Slider Type
    columnSuffix: rzfhsukk
    contentColumnType: string
    fieldGroup: null
    handle: sliderType
    instructions: null
    name: 'Slider Type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Slideshow (1 image per slide, pagination & arrows)'
            -
              - value
              - slideshow
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Carousel (2 images per slide, progress bar)'
            -
              - value
              - carousel
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  017fdb0e-1650-4bed-aa88-2320f4c5101a: # Block Background Colour
    columnSuffix: qiweyybf
    contentColumnType: string
    fieldGroup: null
    handle: blockBackgroundColour
    instructions: 'Block background colour will only be visible for the contained version of this block.'
    name: 'Block Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'White (default)'
            -
              - value
              - light
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  78b7ec25-ca51-442f-81b1-516f79f96d66: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:88345c9b-bba7-481d-b7be-a56f256bad79' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:56f30d52-cee5-4f1a-b135-27ad8bbe2ad9' # Meta
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:88345c9b-bba7-481d-b7be-a56f256bad79' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageSlideshow
name: 'Image Slideshow'
sortOrder: 6
