field: e04fa217-fc47-4d88-a1a5-9c4161a82be9 # Career Content Blocks
fieldLayouts:
  d1df2398-d7a2-422b-ba5c-9c73ecb28913:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ea2089d4-1f26-4ba9-9e61-f83afadca498 # Statement Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bac96a23-fa06-45b3-8d40-f0ee43a73e4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a7db17b-2222-4756-8951-97e810b7d7c2 # Statement Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5385ac9-107e-4c2c-ae60-c4671b57c124
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96a6aa7c-bf62-4631-bf4b-8b21638ea839
        userCondition: null
fields:
  4a7db17b-2222-4756-8951-97e810b7d7c2: # Statement Caption
    columnSuffix: ychcyxtl
    contentColumnType: text
    fieldGroup: null
    handle: statementCaption
    instructions: null
    name: 'Statement Caption'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ea2089d4-1f26-4ba9-9e61-f83afadca498: # Statement Text
    columnSuffix: xajdudcj
    contentColumnType: text
    fieldGroup: null
    handle: statementText
    instructions: null
    name: 'Statement Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: statement
name: Statement
sortOrder: 2
