field: 2fb3dcfb-de61-404d-a714-a5cc5585bc1d # Content Blocks
fieldLayouts:
  63cc5826-1c19-4ee1-9b79-3d8bbf8e09fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 30cc7a46-25b5-4389-8d03-63a08439e958 # Block Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b80017c-d9e0-4e95-ad73-751835cdf6a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2271f307-8c2f-4514-a1db-1ff4a135acf1 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ff1a8e0-6eb2-4069-8e92-32a1d645227c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90672d18-dc74-4505-bff2-b45dbb6ab52e
        userCondition: null
fields:
  30cc7a46-25b5-4389-8d03-63a08439e958: # Block Background Colour
    columnSuffix: vqmtlcek
    contentColumnType: string
    fieldGroup: null
    handle: blockBackgroundColour
    instructions: null
    name: 'Block Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'White (default)'
            -
              - value
              - light
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  2271f307-8c2f-4514-a1db-1ff4a135acf1: # Text
    columnSuffix: dhesfowb
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textSingleColumn
name: 'Text (Single Column)'
sortOrder: 1
