field: e04fa217-fc47-4d88-a1a5-9c4161a82be9 # Career Content Blocks
fieldLayouts:
  d9c7f40c-cb7f-4a02-a90f-2098e7d9ac87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a1cca0bf-7915-42f2-afe2-7cfef2ca16e1 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 032bbe41-52c6-4548-817a-6ed6355efa39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 720de8e9-7686-468b-889a-593ed26a821c
        userCondition: null
fields:
  a1cca0bf-7915-42f2-afe2-7cfef2ca16e1: # Text
    columnSuffix: torbhbob
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textBlock
name: Text
sortOrder: 1
