field: 2fb3dcfb-de61-404d-a714-a5cc5585bc1d # Content Blocks
fieldLayouts:
  cb900080-3622-44c2-845b-c3da0097b74f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 124ff1fb-e849-4d19-9f06-1ca2cf7bc8b3 # Block Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85eae4b2-7451-45e4-8b22-717dd7aeec1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2c85f09-8bef-4517-8214-c3578c40e695 # Block Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d28744ba-99ed-4395-b85b-802312180993
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e31a3c8c-e7f8-4b46-ad11-df7eb18d591e # Left column text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec088fc1-a381-48d9-b527-c671e2f91dcb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 95e390a4-38aa-4707-85aa-975f59abc835 # Right column text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4544ae98-6234-462e-9547-db10171a9605
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8e19f6e5-6407-4e22-bb6d-80f2fa61c960
        userCondition: null
fields:
  95e390a4-38aa-4707-85aa-975f59abc835: # Right column text
    columnSuffix: ctbdmygm
    contentColumnType: text
    fieldGroup: null
    handle: rightColumnText
    instructions: null
    name: 'Right column text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  124ff1fb-e849-4d19-9f06-1ca2cf7bc8b3: # Block Background Colour
    columnSuffix: xkdsirwy
    contentColumnType: string
    fieldGroup: null
    handle: blockBackgroundColour
    instructions: null
    name: 'Block Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'White (default)'
            -
              - value
              - light
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  a2c85f09-8bef-4517-8214-c3578c40e695: # Block Title
    columnSuffix: lvwigoqu
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: 'If used, shows above two columns as a full-width area.'
    name: 'Block Title'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e31a3c8c-e7f8-4b46-ad11-df7eb18d591e: # Left column text
    columnSuffix: qczwmuqf
    contentColumnType: text
    fieldGroup: null
    handle: leftColumnText
    instructions: null
    name: 'Left column text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textDoubleColumn
name: 'Text (Double Column)'
sortOrder: 2
