field: e04fa217-fc47-4d88-a1a5-9c4161a82be9 # Career Content Blocks
fieldLayouts:
  60759b76-3835-4649-8c64-c3fa6ebf604a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf010d9f-f05f-4ec8-80dc-8358b618a9e7 # Video File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1e76132-ff14-4d8c-814d-d4ce1694c5af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 874b42ac-4446-4e02-b289-b7ac6aeac728
        userCondition: null
fields:
  bf010d9f-f05f-4ec8-80dc-8358b618a9e7: # Video File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoFile
    instructions: null
    name: 'Video File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:56f30d52-cee5-4f1a-b135-27ad8bbe2ad9' # Meta
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:132246f9-c0e6-4f99-a712-62365f4bf939' # Videos
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: videoUpload
name: 'Video (upload)'
sortOrder: 5
