field: 2fb3dcfb-de61-404d-a714-a5cc5585bc1d # Content Blocks
fieldLayouts:
  50c53640-ea16-40dc-abca-79f4ea56244d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f052d2f9-01fa-4193-869e-6eac9acdf651 # Block Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ada12b7-4d23-49d3-895b-52e6b485eed4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a392aaa4-4e63-4a27-94a2-cfb9b0bd1684 # Block Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a624175c-bae9-42af-bfd1-d394797069a3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 463bfb9d-3f36-49ce-b8cc-485d9e11122d # Embed code
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 614b9b06-d83c-4447-bb86-2a7eced2f33e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86146a9d-7235-4070-8f01-c6e22e704c5a
        userCondition: null
fields:
  463bfb9d-3f36-49ce-b8cc-485d9e11122d: # Embed code
    columnSuffix: lgwocupq
    contentColumnType: text
    fieldGroup: null
    handle: embedCode
    instructions: null
    name: 'Embed code'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a392aaa4-4e63-4a27-94a2-cfb9b0bd1684: # Block Width
    columnSuffix: rqroggpi
    contentColumnType: string
    fieldGroup: null
    handle: blockWidth
    instructions: null
    name: 'Block Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full width'
            -
              - value
              - fullWidth
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Contained
            -
              - value
              - contained
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  f052d2f9-01fa-4193-869e-6eac9acdf651: # Block Background Colour
    columnSuffix: cbllvjaf
    contentColumnType: string
    fieldGroup: null
    handle: blockBackgroundColour
    instructions: 'Block background colour will only be visible for the contained version of this block.'
    name: 'Block Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'White (default)'
            -
              - value
              - light
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: videoEmbed
name: 'Video (embed)'
sortOrder: 9
