fieldLayouts:
  6f34e909-c840-4c6b-88bf-66ac22aac7cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'The page title will have "Briefing Form" appended to it, so you only need to enter the type e.g. "Animation", "Brand" etc.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0296d69-78c7-4033-9790-721df681f5bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e42d781-7ec4-4ffc-bcb0-b0990f578c4b # Text Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c243744e-041e-42a9-bf26-7aff43c8381b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f957332-91de-4931-b907-dd4e99714a3f # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa979347-a79d-4c08-8e5a-4cd910999581
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 522531d4-4228-4be6-b883-18908eae0b28
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b613214a-51ce-444e-823e-fba5b6dd7ee2 # Briefing Forms
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
