fieldLayouts:
  1e0fdf0e-73ee-4cf1-85b8-816bc2141f38:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ef7de60-9b40-4b77-9a6e-6dda743124e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ee33dc6-65da-4bc3-8a64-ad85d9832bdf # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39c601f4-3ba5-4a93-bb84-fb42aa3abab6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae375820-3398-4233-97c9-880f9bc88381 # Hero Image
            instructions: 'If using a video, you should still upload a Hero Image here as it will be used as the video placeholder, which shows whilst the video is loading in the browser.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af357343-6755-4012-9bda-2946db1b500e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: faf98929-acbc-4d0a-a6c6-636be44b0f74 # Hero Video (Clip)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c9f1363-58ac-499e-aaea-f3f17809a5a0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0d84188a-d34e-4643-a5af-190572cbcb39 # Hero Video (Full Length)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99e3278a-4288-4ca3-b93e-420609ebfdc4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8e3ecc02-7b87-45f0-a999-4d6717f0a872
            userCondition: null
          -
            elementCondition: null
            fieldUid: 46d39a5a-5a05-4341-800c-fec3d516f08c # Intro Text (Left Column)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 550d206f-70dc-4729-95dc-36e1e87dcd4d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0499b203-3226-46f7-a942-f210773facd9 # Intro Text (Right Column)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9719c448-a712-454e-aa00-dd89a304c53b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2d394a2c-b49d-4456-bc8a-20f9f3153ec7
            userCondition: null
          -
            elementCondition: null
            fieldUid: 1e9e0128-1168-4d1f-bb4a-207db0c1ec46 # Selected Projects
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ae27642-45dc-4c13-991e-2667aeaa39f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: eab10f32-7ab2-461d-b87c-31923ffbd204
            userCondition: null
          -
            elementCondition: null
            fieldUid: c716f0ad-a801-4104-bfa5-e8269e480d7e # Client Logos
            instructions: "* Selecting 10 or more logos will automatically split the logo slider into two sliders.\r\n* Double click a logo asset to add an external link to the client's website, if desired.\r\n* Logos should be cropped edge-to-edge i.e. no white space around the outside."
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb6ebab7-3d11-4045-a691-142c20ab832e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 420dd59d-d1c9-481e-98b3-a2706347fbfa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42d3d29f-acd5-4355-b756-dd24a263cf34 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 401c64be-346c-4ca3-9ee1-77dbbcf62aa4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1013d0af-42f2-4277-8692-ca5f66ef4588 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06233fd4-4b85-4345-ad66-0354d8bdbdf9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 225d43ff-b622-4780-8602-22940bb83e3e # OG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac0df31-45af-4f3f-a23b-1d07e01e5002
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 463c567a-fc96-4e79-9520-d157b684ccf4
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: a43126cb-dffe-46f6-b313-3aed439853e8 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
