fieldLayouts:
  dc3d6af0-a1fe-4269-902b-ad1a1c1e2c62:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7227089-58d5-40cf-adce-a9c9b64245ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ee33dc6-65da-4bc3-8a64-ad85d9832bdf # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09c2d8ed-f7fb-47e0-aeac-d74e27aa1343
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae375820-3398-4233-97c9-880f9bc88381 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6824ce76-d3f7-4236-8019-cd292ba8bea2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 000c4a94-5161-4498-89db-9414a8c6ed36 # Greyscale Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cf66a60-5b4c-41d5-918e-6ea54a741438
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 89a4bc35-3d13-49f6-afbb-bc07bbc32fbe
            userCondition: null
          -
            elementCondition: null
            fieldUid: 46d39a5a-5a05-4341-800c-fec3d516f08c # Intro Text (Left Column)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fbc97c9-a439-46ca-9468-2e3ee2cd728a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0499b203-3226-46f7-a942-f210773facd9 # Intro Text (Right Column)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3c78639-8b74-4431-bf26-f664b6c19a8e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 55b7ce4d-6e65-444f-8835-6d40f79ef302
            userCondition: null
          -
            elementCondition: null
            fieldUid: c716f0ad-a801-4104-bfa5-e8269e480d7e # Client Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6bb3fc1-6bc9-4cb4-b256-60265ee766b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5a0f2ed-e196-41e9-b290-96ac1f403915
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d97cab54-76a8-4280-942d-c59ce888204e # Sound Studio Samples
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15cd7f4c-1c3e-492c-a233-d3e8aa729d1d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7ec496b3-3068-4588-910f-eb1bbefd6e4f
            userCondition: null
          -
            elementCondition: null
            fieldUid: c5d8b915-06eb-42e2-b071-c4543ee06156 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7311fa4-bcea-45ec-94db-d9e472a85a0e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7306e119-774f-47f2-80ce-a9d06f969bd2
            userCondition: null
          -
            elementCondition: null
            fieldUid: 98c3f6fb-bcbc-4f96-9786-f6a8c6bb88ac # Sound Studio Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a29e88a6-8f5a-4b3c-8342-25c91001bbc5
            userCondition: null
            warning: null
            width: 100
        name: 'Sound Studio Content'
        uid: 3302a5b7-991d-4adc-8ac4-99fd2bb8d4b3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42d3d29f-acd5-4355-b756-dd24a263cf34 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bda2af14-b6ba-44fa-93f1-aa395a5e99cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1013d0af-42f2-4277-8692-ca5f66ef4588 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad6b5837-dab6-4c20-bf72-2c0e4aa33eac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 225d43ff-b622-4780-8602-22940bb83e3e # OG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c6ae8fc-5bfd-407b-873a-cebd60883504
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 74f98734-f9d7-473a-b767-793e48ef729c
        userCondition: null
handle: soundStudio
hasTitleField: false
name: 'Sound Studio'
section: c19c1dc9-fcdf-41c2-a49a-222e0cbed0db # Sound Studio
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
