fieldLayouts:
  64e5f825-37a8-40be-8592-137bd8c4deb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b39e702e-b603-459e-97a7-1cd459d0ebb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b7ff2db-acac-4df8-b77b-9ee589570a61
        userCondition: null
fs: careerApplicationFiles
handle: careerApplicationFiles
name: 'Career Application Files'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
