fieldLayouts:
  9a29fbd1-9e49-41ff-b164-6732e63e5706:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f5af8b6f-3cc6-45fd-b0a6-06d06ccbfc63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20675af5-e003-413c-b2e8-299de178ad9a # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e52951c-269e-4c44-8848-9aebaf28a803
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f18e760-34c0-4b0d-8d7b-034c6936d10b
        userCondition: null
fs: clientLogos
handle: clientLogos
name: 'Client Logos'
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
