columnSuffix: iugrdetn
contentColumnType: text
fieldGroup: a57e9e8d-4692-4656-b269-1682179f4fc2 # Globals
handle: address
instructions: null
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
