columnSuffix: null
contentColumnType: string
fieldGroup: f8e8eec1-974e-4485-8dc8-e4cd25204baa # Common
handle: category
instructions: null
name: Category
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Select a category'
  showSiteMenu: true
  source: 'group:67a7b2dc-406c-4fce-8de7-33f2740de892' # Newsroom Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
