columnSuffix: dgfxbkfc
contentColumnType: text
fieldGroup: f8e8eec1-974e-4485-8dc8-e4cd25204baa # Common
handle: introTextLeftColumn
instructions: null
name: 'Intro Text (Left Column)'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Custom.json
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
