columnSuffix: ehovtocs
contentColumnType: text
fieldGroup: f8e8eec1-974e-4485-8dc8-e4cd25204baa # Common
handle: pageTitle
instructions: "• If left blank the entry name will be used automatically\r\n• This only affects the H1 (main heading) of the page and will not change the URL"
name: 'Page Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
