columnSuffix: fvyikcls
contentColumnType: boolean
fieldGroup: 3724a7d8-69f4-4e01-a414-e8be3d0abae0 # Settings
handle: redirectToFirstChildPage
instructions: null
name: 'Redirect to First Child Page'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
