dateModified: 1689867811
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Structures
      type: heading
    -
      key: 'section:e5f1c294-aa5c-4406-a9a3-d5a067e2efc0' # Pages
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:8b8e90e2-3152-4e63-8145-70715f8d6116' # Projects
      tableAttributes:
        - dateCreated
        - dateUpdated
        - slug
        - link
      type: native
email:
  fromEmail: me@gracecoote.co.uk
  fromName: 'Craft Base'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  meta:
    hasUrls: true
    name: Meta
    settings:
      path: '@webroot/assets/cms/meta'
    type: craft\fs\Local
    url: '@web/assets/cms/meta'
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/assets/cms/uploads'
    type: craft\fs\Local
    url: '@web/assets/cms/uploads'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: '@webroot/assets/cms/videos'
    type: craft\fs\Local
    url: '@web/assets/cms/videos'
meta:
  __names__:
    0f6d19b5-6f16-45c3-aa26-37159d9c4ba3: 'Favicon 36x36' # Favicon 36x36
    0f8100aa-dfeb-4c7a-a612-34bcba4bf7d2: 'Newsroom Articles' # Newsroom Articles
    0f735174-35bc-45bd-971e-300c7e9cd70e: Statistics # Statistics
    2d5a07da-da97-4edf-89e7-536ff13bb1cd: 'Email Address' # Email Address
    2dd14558-c290-4b79-a4af-255dd2064f55: 'Block Background Colour' # Block Background Colour
    2fb3dcfb-de61-404d-a714-a5cc5585bc1d: 'Content Blocks' # Content Blocks
    3b22405f-25c4-4f1c-88a6-76cbbdff664c: TikTok # TikTok
    3c451390-36bf-41a6-910d-d4eaa3522dba: 'Theme Colour' # Theme Colour
    3f4faf43-dd6f-4014-9d64-8e145bb17352: 'Thumb 960 x 540' # Thumb 960 x 540
    3f57fe1a-2538-4db3-976c-a42769a21b7a: YouTube # YouTube
    4af96521-49a1-4757-8b37-7a72e5763e1f: Address # Address
    4c1526fd-e9b3-4e82-8f78-71a7c5496542: 'Block Background Colour' # Block Background Colour
    4f7797e5-910f-4536-9243-f9c5cfcda4d5: Instagram # Instagram
    5b7711cc-caf3-471b-a459-8815f72b1376: Statistic # Statistic
    5ccaadee-7b10-480c-882e-ed56169d88b0: Images # Images
    5f77600e-9c97-45c6-ae67-f6d2bb6e0e4e: 'Video (embed)' # Video (embed)
    6b2a9aec-c384-408b-946c-3cbaba877529: 'Redirect to First Child Page' # Redirect to First Child Page
    6bf02326-b759-447d-bc08-0892b1fd65b7: 'Favicon 152x152' # Favicon 152x152
    6c273e0a-2f13-4c11-a6b7-fdd82aa39566: 'Text (Single Column)' # Text (Single Column)
    006e61d0-26c0-4fb2-8bcd-ed60efa1e12e: 'Block Background Colour' # Block Background Colour
    7b48acb6-0409-495d-a9ca-d572373e8e89: 'Image Thumbnail' # Image Thumbnail
    7bee1e32-7f18-4448-95ee-9cfc3b0ed3db: 'Block Width' # Block Width
    7bf25c78-6521-4c16-92af-00826343b035: Work # Work
    7f2c84a0-f102-4d22-9635-5948fed536c7: 'Thumb 480 x 270' # Thumb 480 x 270
    8b8e90e2-3152-4e63-8145-70715f8d6116: Projects # Projects
    8e4f3c2b-86b9-4c29-acb8-b289f448993c: 'Favicon 310x150' # Favicon 310x150
    9d5b7bdf-f496-41e6-8afb-6e4e7028332b: 'Favicon 57x57' # Favicon 57x57
    9e42d781-7ec4-4ffc-bcb0-b0990f578c4b: 'Text Block' # Text Block
    13be2e61-d618-4252-b6bb-59f5a19ed677: Newsroom # Newsroom
    14a88088-f556-42bf-976b-d48a31d3e122: Address # Address
    16bbca3c-0a97-487f-a802-b8eac447add5: 'Favicon 144x144' # Favicon 144x144
    17a9a7b1-15f5-4e06-ab52-b257da65e4a1: 'Company name' # Company name
    017fdb0e-1650-4bed-aa88-2320f4c5101a: 'Block Background Colour' # Block Background Colour
    27f6f607-d6b3-4571-8764-4e16a46f960b: 'Video Embed' # Video Embed
    30cc7a46-25b5-4389-8d03-63a08439e958: 'Block Background Colour' # Block Background Colour
    34a6fa50-a3fc-49eb-979d-fc3c712f45c7: 'Favicon SVG' # Favicon SVG
    42d3d29f-acd5-4355-b756-dd24a263cf34: 'SEO Title' # SEO Title
    46a718b9-7e17-42a2-a4ce-3b0214a27bdc: Default # Default
    47b5b191-b5ab-4a7f-b5d0-9b369c81e457: 'Location Name' # Location Name
    051c4e66-a3c8-411d-8e42-c93258e697c9: Twitter # Twitter
    52dcff48-c8a2-4b4e-84db-3e4b87968d8b: Work # Work
    56f30d52-cee5-4f1a-b135-27ad8bbe2ad9: Meta # Meta
    62f1186e-e262-46b5-93a1-81ed960fc6a3: Facebook # Facebook
    63b249c2-c5f1-47b9-b7ec-7d80d06bec66: 'Text (Double Column)' # Text (Double Column)
    70d15b4f-fa51-414d-9d0e-372db863492e: Images # Images
    78b7ec25-ca51-442f-81b1-516f79f96d66: Image(s) # Image(s)
    95e390a4-38aa-4707-85aa-975f59abc835: 'Right column text' # Right column text
    124ff1fb-e849-4d19-9f06-1ca2cf7bc8b3: 'Block Background Colour' # Block Background Colour
    225d43ff-b622-4780-8602-22940bb83e3e: 'OG Image' # OG Image
    463bfb9d-3f36-49ce-b8cc-485d9e11122d: 'Embed code' # Embed code
    537e669b-1f9a-48d9-b740-bf2920a1f4b5: Project # Project
    721c991d-83b0-44ba-87e5-feaf81b49043: Page # Page
    756d642c-6246-4f4e-8537-32630250456f: 'Favicon 16x16' # Favicon 16x16
    812ed655-de97-4974-b556-2b648aa8d926: 'Google Maps Link' # Google Maps Link
    918a41b0-2cc1-4437-a0d9-20d8124c2318: 'Favicon .ico' # Favicon .ico
    1013d0af-42f2-4277-8692-ca5f66ef4588: 'SEO Description' # SEO Description
    1463eb46-b3bc-45c9-81a3-b89fcb1727aa: 'Thumb 512 x 288' # Thumb 512 x 288
    1618d009-643f-4c8c-a421-cc3b3730bac6: Locations # Locations
    1983e86c-24df-47ad-b8e6-347b4fb66f50: 'Block Width' # Block Width
    2271f307-8c2f-4514-a1db-1ff4a135acf1: Text # Text
    3724a7d8-69f4-4e01-a414-e8be3d0abae0: Settings # Settings
    4179e405-630f-4c2b-ba32-66e421c7ad1f: Statement # Statement
    5638a993-1e91-47fc-93a6-f7c52f789aae: Favicon # Favicon
    6062bc9a-a4e5-4395-9fc7-823621507cec: 'Craft Base' # Craft Base
    8728a9f7-bd9c-4bd8-b47d-c25c941ba8af: Vimeo # Vimeo
    9794a518-fb48-48da-ac7d-b4b99fb966ad: 'Block Width' # Block Width
    88345c9b-bba7-481d-b7be-a56f256bad79: Uploads # Uploads
    132246f9-c0e6-4f99-a712-62365f4bf939: Videos # Videos
    472533a5-38cd-464c-bd82-10d58ab4079a: LinkedIn # LinkedIn
    558289e0-2263-4114-af78-ce71e894cf10: 'Favicon 180x180' # Favicon 180x180
    a0ad2a73-81a4-46fe-b8e7-6083409f70e5: 'Favicon 70x70' # Favicon 70x70
    a00b4dca-f148-4c1c-8106-496f60a0a78c: Newsroom # Newsroom
    a2c85f09-8bef-4517-8214-c3578c40e695: 'Block Title' # Block Title
    a3e0dba9-74d3-4194-bd3a-ea2696f87086: Article # Article
    a4a25770-eaa8-46ce-8b3b-71a8c8b20614: 'Favicon 32x32' # Favicon 32x32
    a6d4b9df-3107-45d2-ac86-437b4cb6b050: 'Favicon 76x76' # Favicon 76x76
    a8e2e079-7f11-403c-b358-c93b93a0c992: 'Image Carousel' # Image Carousel
    a14c2dbb-8a00-4c4a-b85b-480a97252c6a: 'Favicon 310x310' # Favicon 310x310
    a57e9e8d-4692-4656-b269-1682179f4fc2: Globals # Globals
    a59ae7c5-8219-4ff7-922e-ec099cf53e73: Image/ImageGrid # Image/ImageGrid
    a392aaa4-4e63-4a27-94a2-cfb9b0bd1684: 'Block Width' # Block Width
    a921cdce-e756-481c-8aac-32ac9dfcd203: Location # Location
    a43126cb-dffe-46f6-b313-3aed439853e8: Home # Home
    ae6c3077-031b-4b16-9ed8-f18ce2d83770: 'Site Info' # Site Info
    ae375820-3398-4233-97c9-880f9bc88381: 'Hero Image' # Hero Image
    b4f2bb50-338e-4111-8725-f254bc3b87b0: Statistic # Statistic
    b919de39-a74a-41ba-8366-3e3bfa181650: 'Favicon 72x72' # Favicon 72x72
    b6822878-090b-45fc-b637-6ccf6bed2f40: Work # Work
    bb59bfee-cc92-4c30-b875-71226f739843: Subtitle # Subtitle
    bc7dee95-9e7b-471a-9e0b-7774fffe011c: 'Block Background Colour' # Block Background Colour
    bd6955ac-0003-4c1c-855f-6986ed631bc4: 'Telephone Number' # Telephone Number
    c0a664fa-02e9-49fc-9a02-c55cf19ba5ca: 'Phone Number' # Phone Number
    c7bbf02b-9a9d-47d2-acd0-5548c7e59e93: 'Favicon 120x120' # Favicon 120x120
    c9a82cb7-7e57-4b48-aa3f-09cea62cacc3: 'Show in footer navigation' # Show in footer navigation
    c12d1e3d-e58f-4496-92e0-d181974b2db9: 'Block Background Colour' # Block Background Colour
    c39129fa-e86f-49ce-9bcf-bf1043c6ed94: 'Suggested Projects' # Suggested Projects
    c9747613-724c-481e-b4ac-2cf6fb4c8c72: Pinterest # Pinterest
    cbb11be7-7020-4487-a344-b7f5808868ad: 'Thumb 1920 x 1080' # Thumb 1920 x 1080
    cecf5c92-7e2f-46fa-a2bf-8334c0c84de4: 'Favicon 150x150' # Favicon 150x150
    d015ca1c-2019-49d3-9c26-0ab619a84fc3: Home # Home
    d0590c29-504c-4f5f-83a0-93784d634ee4: 'Video Thumbnail - Vimeo Link' # Video Thumbnail - Vimeo Link
    d2b05ed8-fe5b-4f5a-b9ab-63bb405d4f49: 'Statistic Caption' # Statistic Caption
    d5a805fd-ad91-4501-b8d3-b8b1efada646: 'Slide Type' # Slide Type
    d6daaff4-e52d-4539-9f6c-285af2414d68: 'Favicon 192x192' # Favicon 192x192
    d8a0c075-0ea5-4aa4-838d-233574d0c90c: 'Image Slideshow' # Image Slideshow
    d37dbdf3-6a11-47f1-b913-e2114f3f3191: 'Video File' # Video File
    d4243c19-5c01-4c63-9754-11d398a4cbac: Meta # Meta
    dbb4a582-e95f-47f0-bc3e-7a176a701c48: 'Craft Base' # Craft Base
    de3ccf4a-2099-429b-b6e3-b22e743240b1: 'Statement Caption' # Statement Caption
    e0ad5847-624f-42b2-ab69-e3bd107d6e44: 'Thumb 768 x 432' # Thumb 768 x 432
    e5eb5006-ee2c-454c-9cfa-2da9a96caeb2: 'Favicon 60x60' # Favicon 60x60
    e5f1c294-aa5c-4406-a9a3-d5a067e2efc0: Pages # Pages
    e31a3c8c-e7f8-4b46-ad11-df7eb18d591e: 'Left column text' # Left column text
    e203826d-16fa-45ed-9c14-78c4c523915f: 'Video (upload)' # Video (upload)
    eb68d48e-ca63-4037-9bbb-0a6580a38e74: Thumbnail # Thumbnail
    eda73b36-d0bf-4823-b7d5-50bf402b5cae: 'Favicon 48x48' # Favicon 48x48
    efad4e89-5ff2-478f-b38b-09d1880c0021: 'Favicon 96x96' # Favicon 96x96
    f052d2f9-01fa-4193-869e-6eac9acdf651: 'Block Background Colour' # Block Background Colour
    f4e9240f-b845-4e24-a506-4091720ce1b9: 'Thumb 1280 x 720' # Thumb 1280 x 720
    f8e8eec1-974e-4485-8dc8-e4cd25204baa: Common # Common
    f558bff2-7034-4fce-a016-3fbb6958f1c5: 'Video Thumbnail (upload)' # Video Thumbnail (upload)
    f605f0a4-4e31-42c7-b69b-0887c7cd8e26: 'Statement Text' # Statement Text
    f972ecdc-6372-435c-9cfe-234fe023396f: 'Favicon 114x114' # Favicon 114x114
    f70343b7-957b-4e91-a5d3-1c560e0757ce: 'OG image' # OG image
    fcd3e3da-9055-422e-9d2a-e8b36f656e93: 'Email Address' # Email Address
plugins:
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: ''
      auto_inject: '1'
      decline: Decline
      defer_js: ''
      disable_in_live_preview: ''
      dismiss: 'Got it!'
      dismiss_on_scroll: '0'
      dismiss_on_timeout: '0'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '365'
      honour_do_not_track_header: ''
      layout: block
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: default
      palette_banner: '000000'
      palette_banner_text: ffffff
      palette_button: f1d600
      palette_button_text: '000000'
      palette_left_button_bg: f8e71c
      palette_left_button_text: '000000'
      palette_link: ffffff
      position: bottom
      preload_css: ''
      revokable: ''
      secure_only: ''
      target: _blank
      type: opt-in
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "body.ltr .matrixblock > .titlebar > .preview {\r\n  display: none !important;\r\n}\r\n\r\n.matrixblock .titlebar {\r\n  cursor: pointer;\r\n}\r\n\r\n.matrixblock .titlebar:hover {\r\n  background: #e4edf8;\r\n}"
      cacheBusting: true
      cssFile: ''
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
  matrix-snap:
    edition: standard
    enabled: false
    licenseKey: FWOMJ6QQ5WC5N00NPRQH794U
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Base'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
