currLabel: 'Plugin Store'
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 6
subnavBehaviour: null
type: craft
url: plugin-store
