currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: tree
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 7
subnavBehaviour: null
type: craft
url: categories
