currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: 1
prevParent: null
prevUrl: globals
sortOrder: 2
subnavBehaviour: null
type: craft
url: globals
