currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 5
subnavBehaviour: null
type: craft
url: settings
