currLabel: Spam
customIcon: null
enabled: true
handle: spam
icon: null
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 2
newWindow: false
parent: 00368c20-6b8d-4805-ad1d-b03c9418250f
prevLabel: Spam
prevLevel: 2
prevParent: 00368c20-6b8d-4805-ad1d-b03c9418250f
prevUrl: freeform/spam
sortOrder: 12
subnavBehaviour: null
type: plugin
url: freeform/spam
