currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: 46a718b9-7e17-42a2-a4ce-3b0214a27bdc # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 4
subnavBehaviour: null
type: craft
url: utilities
