defaultPlacement: end
enableVersioning: true
handle: careersRoles
name: 'Careers - Roles'
propagationMethod: all
siteSettings:
  dbb4a582-e95f-47f0-bc3e-7a176a701c48: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: careers/_entry.html
    uriFormat: 'careers/{slug}'
structure:
  maxLevels: null
  uid: 61d0100a-0460-4d1b-a418-d64fd0c40af0
type: structure
