defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  dbb4a582-e95f-47f0-bc3e-7a176a701c48: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _singles/contact.html
    uriFormat: contact
type: single
