defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  dbb4a582-e95f-47f0-bc3e-7a176a701c48: # Craft Base
    enabledByDefault: true
    hasUrls: true
    template: _singles/home.html
    uriFormat: __home__
type: single
