defaultPlacement: end
enableVersioning: true
handle: newsroomArticles
name: 'Newsroom Articles'
propagationMethod: all
siteSettings:
  dbb4a582-e95f-47f0-bc3e-7a176a701c48: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: newsroom/_entry
    uriFormat: 'newsroom/{slug}'
structure:
  maxLevels: null
  uid: 02c8cc1d-4d90-48fc-aa5e-4956d0ca4116
type: structure
